spring.application.name=restomap-backend
# URL de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/restomap_db
# Le nom d'utilisateur PostgreSQL
spring.datasource.username=postgres
# Le mot de passe
spring.datasource.password=root
# Hibernate créer les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
# Affiche les requêtes SQL dans la console pour débugger
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
