spring.application.name=restomap-backend
server.port=${PORT:6101}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/restomap_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
 spring.jpa.properties.hibernate.format_sql=false
 spring.jpa.properties.hibernate.generate_statistics=false
 spring.mvc.problemdetails.enabled=false

# Configuration HikariCP (économiser le quota Neon)
spring.datasource.hikari.minimum-idle=${NEON_MINIMUM_IDLE:0}
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.keepalive-time=0
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.maximum-pool-size=5

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}